version: "2"
run:
  modules-download-mode: readonly
linters:
  default: all
  disable:
    - depguard
    - noinlineerr
    - paralleltest
    - revive
    - testpackage
    - varnamelen
  exclusions:
    warn-unused: true
    rules:
      - linters:
          - err113
        path: _test.go
